### PR TITLE
Stagger and step method to approximate chaotic saddles.

### PR DESCRIPTION
**Pull request by awage**
This is a first implementation of the Stagger-and-step method referred in issue [JuliaDynamics/Attractors.jl#118](https://github.com/JuliaDynamics/Attractors.jl/issues/118). 

This implements the basic method of Sweet et al. (http://dx.doi.org/10.1103/PhysRevLett.86.2261) but will be soon extended to include parts of the paper [http://dx.doi.org/10.1063/1.4973235](http://dx.doi.org/10.1063/1.4973235)

There is an example in 2D but it should work in any dimension right now. 

I don't know if ChaosTools or Attractors.jl is the right repository.

### CODE REVIEW

**Comment by awage** [comment]
This PR is still a WIP, don't review yet.

**Comment by awage** [comment]
The code is functionnal. There is an example file to generate the doc example. Is there a doc template?

**Comment by Datseris** [comment]
@awage can you move this to Attractors.jl? I'd kindle ask @reykboerner to review it there. I am sorry, I am so utterly swamped I won't be able to review this perhaps until September :(

**Comment by reykboerner** [comment]
Sure, I can take a look at this PR late next week if that's okay @awage.

**Pull request closed without merging**
