### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by spaette**
https://github.com/JuliaDynamics/ChaosTools.jl/issues/304

CHANGELOG.md
<s>docs/src/periodicity.md</s>
src/chaosdetection/expansionentropy.jl
src/chaosdetection/gali.jl
src/chaosdetection/lyapunovs/local_growth_rates.jl
src/chaosdetection/lyapunovs/lyapunov.jl
src/chaosdetection/lyapunovs/lyapunov_from_data.jl
src/chaosdetection/lyapunovs/lyapunovspectrum.jl
src/chaosdetection/partially_predictable.jl
src/chaosdetection/testchaos01.jl
src/dimreduction/dyca.jl
src/periodicity/yin.jl
src/rareevents/mean_return_times/mrt_api.jl
src/rareevents/mean_return_times/mrt_continuous.jl
src/rareevents/mean_return_times/mrt_discrete.jl
src/rareevents/mean_return_times/transit_times_statistics.jl
test/dimreduction/dyca.jl
src/stability/fixedpoints.jl
test/dimreduction/dyca.jl
test/rareevents/return_time_tests.jl

### CODE REVIEW

**Comment by Datseris** [comment]
great, this is good!

**Comment by spaette** [comment]
reverted the mistake changing src/periodicity.md and followed up with a soft reset

unfortunately src/periodicity.md currently shows up in the patch for the Draft PR

that might be interpreted as resulting in a git history which is not clean

the latest comment on the linked to Issue has a shell script with `sed` commands

an additional decision might be made on spelling as `thresold`

`grep -nr thresold ChaosTools.jl`

Should these lines be added to the shell script?

```
sed -i "s/thresold/threshold/g" ChaosTools.jl/src/dimreduction/dyca.jl
sed -i "s/thresold/threshold/g" ChaosTools.jl/test/dimreduction/dyca.jl
```

my preference would be to close this Draft PR and open a new PR for a clean git history

<hr>

> shouldnt change ...words from the DIffEq universe

FWIW, `_affect` not `_effect` appears in this respository's files.

**Comment by Datseris** [comment]
Yes, thesold should also be corrected. Do not worry about opening a new PR. I am squashing anyways so the number of commits doesn't matter.

**Comment by Datseris** [comment]
> possibly [DiffEqBase.jl](https://github.com/SciML/DiffEqBase.jl) here


It's SciMLBase.

**Comment by spaette** [comment]
thesold corrected

errant newline removed (docs/src/periodicity.md no longer appears in patch)

when merged repo should have a git history which is clean

PR has one commit

**Comment by spaette** [comment]
thesold corrected

errant newline removed (docs/src/periodicity.md no longer appears in patch)

when merged repo should have a git history which is clean

PR has one commit

**Pull request merged**
